/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EventContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createEvent"
      | "createEventTicket"
      | "eventTickets"
      | "event_count"
      | "events"
      | "purchaseTicket"
      | "registerForEvent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EventCreated"
      | "EventRegistered"
      | "ticketPurchased"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createEvent",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createEventTicket",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "eventTickets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "event_count",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "events",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTicket",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerForEvent",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEventTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "event_count",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "events", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerForEvent",
    data: BytesLike
  ): Result;
}

export namespace EventCreatedEvent {
  export type InputTuple = [_id: BigNumberish, _organizer: AddressLike];
  export type OutputTuple = [_id: bigint, _organizer: string];
  export interface OutputObject {
    _id: bigint;
    _organizer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventRegisteredEvent {
  export type InputTuple = [
    _id: BigNumberish,
    _guest: AddressLike,
    _timestamp: BigNumberish
  ];
  export type OutputTuple = [_id: bigint, _guest: string, _timestamp: bigint];
  export interface OutputObject {
    _id: bigint;
    _guest: string;
    _timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ticketPurchasedEvent {
  export type InputTuple = [
    _id: BigNumberish,
    _guest: AddressLike,
    _timestamp: BigNumberish
  ];
  export type OutputTuple = [_id: bigint, _guest: string, _timestamp: bigint];
  export interface OutputObject {
    _id: bigint;
    _guest: string;
    _timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventContract extends BaseContract {
  connect(runner?: ContractRunner | null): EventContract;
  waitForDeployment(): Promise<this>;

  interface: EventContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createEvent: TypedContractMethod<
    [
      _title: string,
      _desc: string,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _type: BigNumberish,
      _egc: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createEventTicket: TypedContractMethod<
    [_eventId: BigNumberish, _ticketname: string, _ticketSymbol: string],
    [void],
    "nonpayable"
  >;

  eventTickets: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  event_count: TypedContractMethod<[], [bigint], "view">;

  events: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        _title: string;
        _description: string;
        _startDate: bigint;
        _endDate: bigint;
        _type: bigint;
        _expectedGuestCount: bigint;
        _registeredGuestCount: bigint;
        _verifiedGuestCount: bigint;
        _organizer: string;
        _ticketAddress: string;
      }
    ],
    "view"
  >;

  purchaseTicket: TypedContractMethod<
    [_eventId: BigNumberish, _account: AddressLike],
    [bigint],
    "nonpayable"
  >;

  registerForEvent: TypedContractMethod<
    [_event_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createEvent"
  ): TypedContractMethod<
    [
      _title: string,
      _desc: string,
      _startDate: BigNumberish,
      _endDate: BigNumberish,
      _type: BigNumberish,
      _egc: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createEventTicket"
  ): TypedContractMethod<
    [_eventId: BigNumberish, _ticketname: string, _ticketSymbol: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eventTickets"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "event_count"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "events"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        _title: string;
        _description: string;
        _startDate: bigint;
        _endDate: bigint;
        _type: bigint;
        _expectedGuestCount: bigint;
        _registeredGuestCount: bigint;
        _verifiedGuestCount: bigint;
        _organizer: string;
        _ticketAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "purchaseTicket"
  ): TypedContractMethod<
    [_eventId: BigNumberish, _account: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerForEvent"
  ): TypedContractMethod<[_event_id: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "EventCreated"
  ): TypedContractEvent<
    EventCreatedEvent.InputTuple,
    EventCreatedEvent.OutputTuple,
    EventCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EventRegistered"
  ): TypedContractEvent<
    EventRegisteredEvent.InputTuple,
    EventRegisteredEvent.OutputTuple,
    EventRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ticketPurchased"
  ): TypedContractEvent<
    ticketPurchasedEvent.InputTuple,
    ticketPurchasedEvent.OutputTuple,
    ticketPurchasedEvent.OutputObject
  >;

  filters: {
    "EventCreated(uint256,address)": TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;
    EventCreated: TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;

    "EventRegistered(uint256,address,uint256)": TypedContractEvent<
      EventRegisteredEvent.InputTuple,
      EventRegisteredEvent.OutputTuple,
      EventRegisteredEvent.OutputObject
    >;
    EventRegistered: TypedContractEvent<
      EventRegisteredEvent.InputTuple,
      EventRegisteredEvent.OutputTuple,
      EventRegisteredEvent.OutputObject
    >;

    "ticketPurchased(uint256,address,uint256)": TypedContractEvent<
      ticketPurchasedEvent.InputTuple,
      ticketPurchasedEvent.OutputTuple,
      ticketPurchasedEvent.OutputObject
    >;
    ticketPurchased: TypedContractEvent<
      ticketPurchasedEvent.InputTuple,
      ticketPurchasedEvent.OutputTuple,
      ticketPurchasedEvent.OutputObject
    >;
  };
}
