/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as airdropSol from "./Airdrop.sol";
export type { airdropSol };
import type * as customErc20Sol from "./CustomERC20.sol";
export type { customErc20Sol };
