/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721Sol from "./ERC721.sol";
export type { erc721Sol };
import type * as eventsSol from "./Events.sol";
export type { eventsSol };
export type { MyERC20 } from "./MyERC20";
export * as factories from "./factories";
export type { TicketNFT } from "./ERC721.sol/TicketNFT";
export { TicketNFT__factory } from "./factories/ERC721.sol/TicketNFT__factory";
export type { EventContract } from "./Events.sol/EventContract";
export { EventContract__factory } from "./factories/Events.sol/EventContract__factory";
export { MyERC20__factory } from "./factories/MyERC20__factory";
