/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc721Sol from "./ERC721.sol";
export * as eventsSol from "./Events.sol";
export { MyERC20__factory } from "./MyERC20__factory";
