/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CustomERC20__factory } from "./CustomERC20__factory";
export { ERC20Token__factory } from "./ERC20Token__factory";
